### ISSUE TITLE
Debug messages are being printed when calling CLI

### ISSUE THREAD

**Issue by mayansalama** [Woile/decli#34]
Hi mate,

This is a great extension - however it's printing out DEBUG messages every time it runs. It's easy enough to turn off but I don't think it makes sense for an argparser - usually the first thing called - to be printing out messages. 

Happy to put a pull request through for this.

**Comment by Woile** [comment]
That's true and weird haha sorry, I'm currently in holiday, if you have time make a PR setting it to info, otherwise I'll fix it when I'm back.

Thanks!

**Comment by Woile** [comment]
Version `0.5.1` has been released! now logger is in `INFO` mode. Cheers
